apiVersion: v1
kind: Service
metadata:
  name: hello-world     
labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:                  
    name: hello-world   
  ports:
  - name: web
    port: 8080               
    protocol: TCP
    targetPort: 8080
    nodePort: {{ .Values.nodePort }}
  type: "NodePort"
  sessionAffinity: "None"
