apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: cluster-seed
spec:
  # Add fields here
  templateSource:
    uri: http://localhost:8000
    ref: master
    contextDir: seed/templates
  parameterSource:
    contextDir: seed/parameters
  triggers:
  - type: Change
  - type: Webhook
  - type: Periodic
    cron: "0 * * * *"
  serviceAccountRef: gitops
  templateProcessorImage: quay.io/kohlstechnology/eunomia-base:v0.0.1
  resourceHandlingMode: CreateOrMerge
