apiVersion: v1
kind: ServiceAccount
metadata:
  name: eunomia-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eunomia-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: eunomia-operator
  namespace: eunomia-hello-world-demo
